/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class JokeTellerTest {
    @Test public void testSomeLibraryMethod() {
        JokeTeller jokeTeller = new JokeTeller();
        assertNotNull("getJoke returned null", jokeTeller.getJoke());
    }
}
